#SPDX-License-Identifier: MIT-0
---
# defaults file for sap_hana_bone_partitioning
hosts:
  - localhost
disks:
  - /dev/sdb
lvg_name: "sap"
lvs:
  - name: data
    size: 20G
    fstype: xfs
    mount_point: /hana/data
  - name: log
    size: 30G
    fstype: xfs
    mount_point: /hana/log
  - name: shared
    size: "{{ 1.5 * ansible_facts.memory_mb.real.total }}"
    fstype: xfs
    mount_point: /hana/shared
  - name: usr_sap
    size: 50G
    fstype: xfs
    mount_point: /usr/sap

