#SPDX-License-Identifier: MIT-0
---
# defaults file for sap_hana_bone_partitioning
lv_hana_data_min: 20000 # Minimum 20 GB
lv_hana_data_size: "{{ ansible_facts.memory_mb.real.total | max(lv_hana_data_min) }}"

lv_hana_log_min: 20000 # Minimum 20 GB
lv_hana_log_max: 512000 # Maximum 512 GB
lv_hana_log_size: "{{ (ansible_facts.memory_mb.real.total | min(lv_hana_log_max)) | max(lv_hana_log_min) }}"

lv_hana_shared_min: 20000 # Minimum 20 GB
lv_hana_shared_max: 1000000 # Maximum 1 TB
lv_hana_shared_size: "{{ (ansible_facts.memory_mb.real.total | min(lv_hana_shared_max)) | max(lv_hana_shared_min) }}"

sap_hana_bone_disks:
  - /dev/sdb
sap_hana_bone_lvg_name: "sap"
sap_hana_bone_lvs:
  - name: data
    size: "{{ lv_hana_data_size }}"
    fstype: xfs
    mount_point: /hana/data
  - name: log
    size: "{{ lv_hana_log_size }}"
    fstype: xfs
    mount_point: /hana/log
  - name: shared
    size: "{{ lv_hana_shared_size }}"
    fstype: xfs
    mount_point: /hana/shared
  - name: usr_sap
    size: 50G
    fstype: xfs
    mount_point: /usr/sap

