#SPDX-License-Identifier: MIT-0
---
# defaults file for sap_hana_bone_prepare
#
# Directory containing the IMDB ZIP files and all components
sap_hana_install_software_directory: '/software/hana'

# Directory into which the ZIP files will be extracted. 
sap_hana_install_software_extract_directory: "/software/extracted/hana"

# Directory containing the Sap Bone ZIP files and all components
sap_bone_install_software_directory: '/software/bone'

# Directory into which the archive files will be extracted.
sap_bone_install_software_extract_directory: "/software/extracted/bone"


sap_bone_install_selected_features: B1ServerToolsSLD,B1ServerToolsExtensionManager,B1ServerToolsLicense,B1ServerToolsJobService,B1ServerToolsMobileService,B1ServerToolsXApp,B1SLDAgent,B1WebClient,B1BackupService,B1ServerSHR,B1ServerCommonDB,B1ServerHelp_EN,B1ServerAddons,B1ServerOI,B1AnalyticsOlap,B1AnalyticsTomcatEntSearch,B1AnalyticsTomcatDashboard,B1AnalyticsTomcatReplication,B1AnalyticsTomcatConfiguration,B1AnalyticsTomcatPredictiveAnalysis,B1ServiceLayerComponent,B1ElectronicDocumentService,B1APIGatewayService

hostname: "{{ ansible_facts.fqdn }}"
