#SPDX-License-Identifier: MIT-0
---
# tasks file for sap_bone_install
# sap_bone_install_software_directory
# sap_bone_install_software_extract_directory
name: 1. Check if the the SAR files are enpacked already 
  - 
